//
//  DrawView.h
//  healthca
//
//  Created by Kael on 2016/10/13.
//  Copyright (c) 2016 Skyworth-Hightong. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface DrawView : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* menuBtnTargets;

// Colors
+ (UIColor*)kWhiteColor;
+ (UIColor*)kBlueColor;
+ (UIColor*)kRedColor;

// Drawing Methods
+ (void)drawMenuBtn;

// Generated Images
+ (UIImage*)imageOfMenuBtn;

@end
