//
//  DrawView.m
//  healthca
//
//  Created by Kael on 2016/10/13.
//  Copyright (c) 2016 Skyworth-Hightong. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "DrawView.h"


@implementation DrawView

#pragma mark Cache

static UIColor* _kWhiteColor = nil;
static UIColor* _kBlueColor = nil;
static UIColor* _kRedColor = nil;

static UIImage* _imageOfMenuBtn = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _kWhiteColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    _kBlueColor = [UIColor colorWithRed: 0.059 green: 0.51 blue: 0.898 alpha: 1];
    _kRedColor = [UIColor colorWithRed: 1 green: 0 blue: 0 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)kWhiteColor { return _kWhiteColor; }
+ (UIColor*)kBlueColor { return _kBlueColor; }
+ (UIColor*)kRedColor { return _kRedColor; }

#pragma mark Drawing Methods

+ (void)drawMenuBtn
{

    //// background Drawing
    UIBezierPath* backgroundPath = [UIBezierPath bezierPathWithRect: CGRectMake(0, 0, 50, 44)];
    [DrawView.kBlueColor setFill];
    [backgroundPath fill];


    //// downLine Drawing
    UIBezierPath* downLinePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(9, 30, 32, 3) cornerRadius: 1];
    [DrawView.kWhiteColor setFill];
    [downLinePath fill];


    //// midLine Drawing
    UIBezierPath* midLinePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(9, 20, 32, 3) cornerRadius: 1];
    [DrawView.kWhiteColor setFill];
    [midLinePath fill];


    //// upLine Drawing
    UIBezierPath* upLinePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(9, 10, 32, 3) cornerRadius: 1];
    [DrawView.kWhiteColor setFill];
    [upLinePath fill];
}

#pragma mark Generated Images

+ (UIImage*)imageOfMenuBtn
{
    if (_imageOfMenuBtn)
        return _imageOfMenuBtn;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(50, 44), NO, 0.0f);
    [DrawView drawMenuBtn];

    _imageOfMenuBtn = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfMenuBtn;
}

#pragma mark Customization Infrastructure

- (void)setMenuBtnTargets: (NSArray*)menuBtnTargets
{
    _menuBtnTargets = menuBtnTargets;

    for (id target in self.menuBtnTargets)
        [target setImage: DrawView.imageOfMenuBtn];
}


@end
